export enum JobCategory {
    SoftwareEngineering = 'software_engineering',
    DevOps = 'devops',
    DataScience = 'data_science',
    Cybersecurity = 'cybersecurity',
    CloudComputing = 'cloud_computing',
    NetworkEngineering = 'network_engineering',
    SystemAdministration = 'system_administration',
    DatabaseAdministration = 'database_administration',
    ITSupport = 'it_support',
    UIUXDesign = 'uiux_design',
    ProductManagement = 'product_management',
    QATesting = 'qa_testing',
    MachineLearningAI = 'machine_learning_ai',
    MobileDevelopment = 'mobile_development',
    WebDevelopment = 'web_development',
    ITProjectManagement = 'it_project_management',
    ITArchitecture = 'it_architecture',
    EmbeddedSystemsIoT = 'embedded_systems_iot',
    BlockchainCrypto = 'blockchain_crypto',
    GameDevelopment = 'game_development',
}
